name = "Laws and Discrimination of LGBT in EU (prototype)"
app_id = "a089df38-1395-4e72-82c3-e617ab01cc5d"
app_url = ""
team_id = "f107ea82-9838-4dc5-96ad-a1ca24261efa"
team_name = "Viktoria Lilitskaia's Team"
